# Generated by Django 6.0.1 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settinges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='названия сайти')),
                ('description', models.TextField(verbose_name='описания')),
                ('logo', models.FileField(upload_to='', verbose_name='логотип сайта')),
                ('phone_number', models.CharField(verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('address', models.CharField(verbose_name='физический адрес')),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
    ]
